---
title: "Dati"
author:
  - name: ISPRA 
    affiliation: ISPRA
    affiliation_url: https://www.isprambiente.gov.it/it
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### [Dati inquinanti](./acquisire_dati_inquinanti.html)

- Come scaricare i dati giornalieri degli inquinanti sotto forma di `data frame` per il linguaggio `R`.

- [Aggiornamento](./aggiornamento.html) dei pacchetti. 

- Come risolvere eventuali [problemi di istallazione dei pacchetti R](./problemi_istallazione.html).

### [Parametri meteoclimatici](./acquisire_dati_meteo.html)

Installare il pacchetto R `datiMeteo` contenente i dati giornalieri dei parametri meteoclimatici.

### [Pacchetti R per gli inquinanti](./pacchetti_inquinanti.html)

Descrizione dei dati degli inquinanti e tabella dei pacchetti R disponibili su `github`.

### [Anagrafica delle stazioni](./anagrafica.html)

Acquisire i metadati delle stazioni di monitoraggio.

### [Associare i dati degli inquinanti con i parametri meteoclimatici](./associare.html)

Come fare il `join` tra i dati degli inquinanti e quelli dei parametri meteoclimatici utilizzando il pacchetto `R` `dplyr`.




