---
title: "pulviruS"
description: |
  Il non-sito del progetto di ricerca.
site: distill::distill_website
---

```{r setup, include=FALSE}
library("tidyverse")
library("circlepackeR")
library("data.tree")
library("scico")
knitr::opts_chunk$set(echo = FALSE,include = FALSE,message = FALSE,warning = FALSE,eval=TRUE)

# Learn more about creating websites with Distill at:
# https://rstudio.github.io/distill/website.html

```

```{r}
list.files(pattern="^stazioniValide_.+csv$",path = "assets/",full.names = TRUE)->ffile
stopifnot(length(ffile)!=0)

purrr::map_dfr(ffile,.f=function(nomeFile){
  
  inquinante<-str_remove(str_remove(nomeFile,"^.+stazioniValide_"),"\\.csv$")
  read_delim(nomeFile,col_names = FALSE,delim=";")->dati
  names(dati)<-c("staz_eu_code","completezza","regione")
  dati$inquinante<-inquinante
  
  dati
  
})->finale

finale %>%
  group_by(regione,staz_eu_code,inquinante) %>%
  summarise(numeroStazioni=n()) %>%
  ungroup()->mydf

mydf %>%
  mutate(pathString=paste("pulvirus",regione,staz_eu_code,inquinante,sep="/"))->mydf

as.Node(mydf)->prova
```

```{r,include=TRUE,echo=FALSE,message=FALSE,warning=FALSE,eval=TRUE,fig.height=7,fig.width=7}
circlepackeR(prova,size="numeroStazioni",color_min = "#fae16c",color_max = "#ab3d2f")
```