---
title: "Regioni con dati per gli inquinanti"
description: |
  Pacchetti R disponibili su github con i dati degli inquinanti
author:
  - name: Uncle Tom 
    affiliation: ISPRA
    affiliation_url: https://www.isprambiente.gov.it/it
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Dati inquinanti per PULVIRUS

I dati giornalieri degli inquinanti distribuiti mediante pacchetti R rappresentano un sottoinsieme dei dati disponibili nel database del progetto `PULVIRUS`: si tratta, infatti, delle serie di dati selezionate in base ai [controlli di completezza](completezza.html). 


### Organizzazione dei `data frame`

I `data frame` con i dati degli inquinanti contengono:

- il codice (`pollutant_fk`) dell'inquinante [INSERIRE TABELLA]

- il codice (`station_eu_code`) identificativo della stazione 

- la data (`date`) dell'osservazione nel formato %Y-%m-%d  

- il valore osservato (`value`) dell'inquinante

- il nome della regione (`regione`)

- il giorno (`dd`) dell'osservazione

- il mese (`mm`) dell'osservazione

- l'anno (`yy`) dell'osservazione



### Pacchetti con i dati 

| Regione | Nome Pacchetto | pm10 | pm2.5 | no2 | nox| c6h6 |
| ---     | ---       | --   | --    | --  | -- | -- |
| Basilicata   | basilicata | x  | x   | x   |  x |
| Campania     | campania   |  | x   | x   |    | |
| Emilia Romagna | emiliaromagna | x | x   | x  |  x  | x |
| Friuli Venezia Giulia | friuliveneziagiulia | x | x | | | x |
| Lazio | lazio | x | x | x | x | |
| Lombardia | lombardia | x | x | x | x | x |
| Molise | molise | | | x | x | |
| Bolzano, Provincia Autonoma | pabolzano | x | x | x | | x |
| Trento, Provincia Autonoma | patrento | x | x | x | | x |
| Piemonte | piemonte | x | x | x | | x |
| Puglia | puglia | x | x | x | x | x |
| Sardegna | sardegna | x | x | x | x | x |
| Sicilia  | sicilia | x | x | x | | x |
| Toscana  | toscana | x | x | x | x | |
| Umbria   | umbria  | x | x | x | x | x |
| Valle d'Aosta| valleaosta | x | x | x | | |
| Veneto       | veneto | x | x | x | x | |










