---
title: "Variabili Meteoclimatiche"
author:
  - name: ISPRA
    affiliation: ISPRA
    affiliation_url: https://www.isprambiente.gov.it/it
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

La tabella riassume i parametri meteoclimatici i cui dati giornalieri sono stati estratti dalle rianalisi [ERA5](https://www.ecmwf.int/en/forecasts/datasets/reanalysis-datasets/era5). I dati sono disponibili dal database del progetto PULVIRUS o come data.grame all'interno del pacchetto R `datiMeteo` presso il repository github [progettopulvirus](https://github.com/progettopulvirus/).

| Nome | Codice | Unita | Aggregazione giornaliera |
| ---| --- | --- | --- |
| Surface pressure | sp | hPa | media |
| Average temperature (2m) | t2m | °C | media |
| Maximum temperature (2m) | tmax2m | °C | **massimo giornaliero** |
| Minimum temperature (2m) | tmin2m |  °C | **minimo giornaliero** |
| Planet Boundary Layer ore 00 | pbl00 | km | media o **valore istantaneo** |
| Planet Boundary Layer ore 12 | pbl12 | km | media **valore istantaneo** |
| Planet Boundary Layer daily maximum | pblmax | km | massimo **valore istantaneo** |
| Planet Boundary Layer daily minimum | pblmin | km | minimo **valore istantaneo** |
| Total precipitation | tp | mm | somma |
| Previous day total precipitation | ptp | mm | somma |
| Wind speed | wspeed | m/s | media |
| Previous day wind speed | pwspeed | m/s | media |
| Wind direction | wdir | gradi | **moda** |
| Wind U component (10 meters) | u10m | m/s  | media |
| Wind V component (10 meters) | v10m | m/s  | media |
| Relative Humidity | rh | % | media |
| Wind gust | wgust | m/s | **massimo giornaliero**  | media |
| Net irradiance | nirradiance | W/m^2 | media |




